一些小优化
dogdie233/LiarsBarEnhance pull request #16
Opened 2024-10-23 04:37 UTC by TianMengLucky

2024-10-23 06:52 UTC, dogdie233 requested changes
把这写地方该回去就合并了吧
下次格式化就不要端上来了（）

2024-10-23 06:52 UTC, dogdie233 commented on Plugin.cs
> +        _harmony.PatchAll();
不用PatchAll是因为这样不方便自己开关想要的功能进行编译

2024-10-23 06:52 UTC, dogdie233 commented on Components/FPController.cs
> +                    : _deceleration * Time.deltaTime));
感觉这里格式化完更乱了

2024-10-23 06:54 UTC, dogdie233 commented
沟槽的一行80个字符的规范早该似了

2024-10-23 07:14 UTC, dogdie233 approved these changes
ok nya

2024-10-23 07:14 UTC, merged

2024-10-23 07:15 UTC, dogdie233 commented
三克斯 for your contribution~

2024-10-24 12:26 UTC, dogdie233 commented
怎么改了构建位置不更新README，怒了喵

2024-10-24 20:11 UTC, TianMengLucky commented
> 怎么改了构建位置不更新README，怒了喵

啊，抱歉只改了中文的README